name: safesight
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  supabase: ^2.8.0
  get: ^4.7.2
  http: ^1.4.0
  file_picker: ^10.2.0
  google_sign_in: ^7.2.0
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_datetime_picker_plus: ^2.2.0
  flutter_datetime_picker_bdaya: ^3.0.2
  glassmorphism: ^3.0.0
  lottie: ^3.3.1
  flutter_floating_bottom_bar: ^1.3.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.12.3
  location: ^8.0.1
  flutter_map: ^8.1.1
  sign_in_with_apple: ^7.0.1
  foundation: ^0.0.5
  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/auth/
    - assets/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
